/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WildRouteImport } from './routes/wild'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlayRouteImport } from './routes/play'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GroveRouteImport } from './routes/grove'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForestUsernameRouteImport } from './routes/forest.$username'

const WildRoute = WildRouteImport.update({
  id: '/wild',
  path: '/wild',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GroveRoute = GroveRouteImport.update({
  id: '/grove',
  path: '/grove',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForestUsernameRoute = ForestUsernameRouteImport.update({
  id: '/forest/$username',
  path: '/forest/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/friends': typeof FriendsRoute
  '/grove': typeof GroveRoute
  '/leaderboard': typeof LeaderboardRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/wild': typeof WildRoute
  '/forest/$username': typeof ForestUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/friends': typeof FriendsRoute
  '/grove': typeof GroveRoute
  '/leaderboard': typeof LeaderboardRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/wild': typeof WildRoute
  '/forest/$username': typeof ForestUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/friends': typeof FriendsRoute
  '/grove': typeof GroveRoute
  '/leaderboard': typeof LeaderboardRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/wild': typeof WildRoute
  '/forest/$username': typeof ForestUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/friends'
    | '/grove'
    | '/leaderboard'
    | '/play'
    | '/profile'
    | '/wild'
    | '/forest/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/friends'
    | '/grove'
    | '/leaderboard'
    | '/play'
    | '/profile'
    | '/wild'
    | '/forest/$username'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/friends'
    | '/grove'
    | '/leaderboard'
    | '/play'
    | '/profile'
    | '/wild'
    | '/forest/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FriendsRoute: typeof FriendsRoute
  GroveRoute: typeof GroveRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PlayRoute: typeof PlayRoute
  ProfileRoute: typeof ProfileRoute
  WildRoute: typeof WildRoute
  ForestUsernameRoute: typeof ForestUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wild': {
      id: '/wild'
      path: '/wild'
      fullPath: '/wild'
      preLoaderRoute: typeof WildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grove': {
      id: '/grove'
      path: '/grove'
      fullPath: '/grove'
      preLoaderRoute: typeof GroveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forest/$username': {
      id: '/forest/$username'
      path: '/forest/$username'
      fullPath: '/forest/$username'
      preLoaderRoute: typeof ForestUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FriendsRoute: FriendsRoute,
  GroveRoute: GroveRoute,
  LeaderboardRoute: LeaderboardRoute,
  PlayRoute: PlayRoute,
  ProfileRoute: ProfileRoute,
  WildRoute: WildRoute,
  ForestUsernameRoute: ForestUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
